import { ArrowRight } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { Link } from "react-router-dom";
import { BrandMark } from "@/shared/ui/BrandMark";
import { PublicSiteQrCode } from "@/shared/ui/PublicSiteQrCode";

export function LandingPage() {
  const reduceMotion = useReducedMotion();
  const reveal = reduceMotion ? {} : { initial: { opacity: 0, y: 18 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.7, ease: [0.16, 1, 0.3, 1] as const } };
  return <main className="landing-page relative isolate min-h-[100dvh] overflow-hidden px-5 py-6 text-ink sm:px-8 lg:px-12"><motion.div animate={reduceMotion ? {} : { rotate: 360 }} transition={{ duration: 26, ease: "linear", repeat: Infinity }} aria-hidden="true" className="landing-signal" /><div className="relative mx-auto flex min-h-[calc(100dvh-3rem)] max-w-[88rem] flex-col"><header className="flex items-start justify-between gap-4"><BrandMark /><div className="border-l border-ink/20 pl-3 text-right text-[11px] leading-[1.45] text-muted"><p className="m-0 font-semibold text-ink">Calypso Park</p><p className="m-0">Saturday<br />29 August 2026</p></div></header><div className="grid flex-1 items-center gap-10 py-16 lg:grid-cols-[minmax(0,1.25fr)_minmax(16rem,.55fr)] lg:gap-18"><motion.section {...reveal} className="max-w-3xl"><p className="mb-6 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.14em] text-gold"><span className="h-px w-8 bg-gold" />Inter-House Sports Day</p><h1 className="m-0 max-w-4xl text-balance text-[clamp(4.1rem,9.3vw,9.3rem)] leading-[.84] tracking-[-.09em]">Your house<br /><span className="font-light text-gold">is waiting.</span></h1><p className="mb-8 mt-8 max-w-md text-[17px] leading-relaxed text-muted">Search your name to discover your team, your food assignment, and who to contact on the day.</p><Link className="group inline-flex items-center gap-2 border border-ink bg-ink px-5 py-4 text-[15px] font-bold text-white transition hover:-translate-y-1 hover:bg-[#23336a]" to="/search">Find my house <ArrowRight className="transition-transform duration-300 group-hover:translate-x-1" size={19} /></Link></motion.section><motion.aside {...(reduceMotion ? {} : { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 0.18, duration: 0.8, ease: [0.16, 1, 0.3, 1] as const } })} className="hidden border border-ink/15 bg-white/65 p-6 shadow-[20px_28px_0_rgba(23,37,84,0.08)] backdrop-blur-sm lg:block"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-gold">Scan to begin</p><div className="mt-7"><PublicSiteQrCode /></div><p className="mb-0 mt-5 text-3xl tracking-[-.07em]">Find your place.</p><p className="mb-0 mt-2 text-sm leading-relaxed text-muted">No login. No app. Just your name.</p></motion.aside></div><footer className="flex items-end justify-between gap-4 text-[11px] text-muted"><p className="m-0">Presbyterian Church of Nigeria</p><p className="m-0 text-right">PYPAN Inter-House Sports Day</p></footer></div></main>;
}
