import { ArrowRight, FileUp, House, List } from "lucide-react";
import { Link } from "react-router-dom";
import { PublicSiteQrCode, PUBLIC_SITE_URL } from "@/shared/ui/PublicSiteQrCode";

const DASHBOARD_ACTIONS = [{ label: "Set up houses", detail: "Create and configure the four house records.", to: "/console/houses", icon: House }, { label: "Upload roster", detail: "Import participants for one configured house.", to: "/console/upload", icon: FileUp }, { label: "Review roster", detail: "Search participant records and reveal status.", to: "/console/roster", icon: List }];

export function ConsoleDashboardPage() {
  return <section className="p-5 sm:p-8"><div className="mx-auto max-w-5xl"><p className="mb-3 text-[11px] font-bold uppercase tracking-[.14em] text-muted">Console overview</p><h1 className="m-0 text-[clamp(2.5rem,6vw,4.5rem)] leading-[.95] tracking-[-.075em]">Prepare the event roster.</h1><p className="mt-5 max-w-xl leading-relaxed text-muted">Set up the houses, load each participant list, and monitor reveal progress from one place.</p><div className="mt-10 grid gap-4 sm:grid-cols-3">{DASHBOARD_ACTIONS.map(({ icon: Icon, label, detail, to }) => <Link className="group rounded-md border border-line bg-white p-5 transition hover:-translate-y-1 hover:border-ink" key={to} to={to}><Icon size={19} /><h2 className="mb-1 mt-8 text-lg tracking-[-.04em]">{label}</h2><p className="m-0 text-sm leading-relaxed text-muted">{detail}</p><ArrowRight className="mt-6 transition-transform group-hover:translate-x-1" size={18} /></Link>)}</div><section className="mt-10 grid items-center gap-8 border border-line bg-white p-5 sm:grid-cols-[1fr_auto] sm:p-7"><div><p className="m-0 text-[11px] font-bold uppercase tracking-[.14em] text-gold">Event QR code</p><h2 className="mb-2 mt-3 text-2xl tracking-[-.05em]">Share the public house reveal.</h2><p className="m-0 max-w-lg text-sm leading-relaxed text-muted">This code opens <a className="font-bold text-ink underline underline-offset-4" href={PUBLIC_SITE_URL}>{PUBLIC_SITE_URL}</a>. Download the SVG or print a ready-to-share event sheet.</p></div><PublicSiteQrCode downloadable printable size={144} /></section></div></section>;
}
